-- ==========================================
-- SEED DATA: Datos oficiales para el sistema
-- ==========================================

-- 1. Insertar Tiendas (79 locales de la Sierra)
INSERT INTO tiendas (id, nombre, ciudad, direccion, unidad, supervisor_nombre) VALUES
(1, 'BODEGA ATAHUALPA (BAT1)', 'Sierra', 'BODEGA ATAHUALPA, Región Sierra', 'BAT1', 'JULIO TUBON'),
(2, 'BODEGA NORTE (BNO1)', 'Sierra', 'BODEGA NORTE, Región Sierra', 'BNO1', 'JULIO TUBON'),
(3, 'BODEGA RIOBAMBA (BRI1)', 'Riobamba', 'BODEGA RIOBAMBA, Región Sierra', 'BRI1', 'JULIO TUBON'),
(4, 'CIKLA CUENCA (CCU1)', 'Cuenca', 'CIKLA CUENCA, Región Sierra', 'CCU1', 'JULIO TUBON'),
(5, 'EXPLORER JARDIN (EJA1)', 'Quito', 'EXPLORER JARDIN, Región Sierra', 'EJA1', 'JULIO TUBON'),
(6, 'EXPLORER MALL DEL RIO (ECU1)', 'Sierra', 'EXPLORER MALL DEL RIO, Región Sierra', 'ECU1', 'JULIO TUBON'),
(7, 'EXPLORER RIOBAMBA (ERI1)', 'Riobamba', 'EXPLORER RIOBAMBA, Región Sierra', 'ERI1', 'JULIO TUBON'),
(8, 'EXPLORER SCALA (ESC1)', 'Quito', 'EXPLORER SCALA, Región Sierra', 'ESC1', 'JULIO TUBON'),
(9, 'MARATHON JARDIN (MJA1)', 'Quito', 'MARATHON JARDIN, Región Sierra', 'MJA1', 'JULIO TUBON'),
(10, 'MARATHON MALL DEL ALTO (MMA1)', 'Sierra', 'MARATHON MALL DEL ALTO, Región Sierra', 'MMA1', 'JULIO TUBON'),
(11, 'MARATHON MALL DEL RIO (MCU1)', 'Sierra', 'MARATHON MALL DEL RIO, Región Sierra', 'MCU1', 'JULIO TUBON'),
(12, 'MARATHON QUICENTRO SUR (MQS1)', 'Quito', 'MARATHON QUICENTRO SUR, Región Sierra', 'MQS1', 'JULIO TUBON'),
(13, 'MARATHON RIOBAMBA (MRI1)', 'Riobamba', 'MARATHON RIOBAMBA, Región Sierra', 'MRI1', 'JULIO TUBON'),
(14, 'MARATHON SCALA (MSC1)', 'Quito', 'MARATHON SCALA, Región Sierra', 'MSC1', 'JULIO TUBON'),
(15, 'OUTLET BATAN (OBT1)', 'Sierra', 'OUTLET BATAN, Región Sierra', 'OBT1', 'JULIO TUBON'),
(16, 'OUTLET GUARANDA (OGU1)', 'Guaranda', 'OUTLET GUARANDA, Región Sierra', 'OGU1', 'JULIO TUBON'),
(17, 'OUTLET MONAY (OMO1)', 'Sierra', 'OUTLET MONAY, Región Sierra', 'OMO1', 'JULIO TUBON'),
(18, 'TAF JARDIN (FJA1)', 'Quito', 'TAF JARDIN, Región Sierra', 'FJA1', 'JULIO TUBON'),
(19, 'TAF QUICENTRO SUR (FQS1)', 'Quito', 'TAF QUICENTRO SUR, Región Sierra', 'FQS1', 'JULIO TUBON'),
(20, 'TELESHOP JARDIN (TJA1)', 'Quito', 'TELESHOP JARDIN, Región Sierra', 'TJA1', 'JULIO TUBON'),
(21, 'TELESHOP QUICENTRO SUR (TQS1)', 'Quito', 'TELESHOP QUICENTRO SUR, Región Sierra', 'TQS1', 'JULIO TUBON'),
(22, 'TELESHOP RIOBAMBA (TRI1)', 'Riobamba', 'TELESHOP RIOBAMBA, Región Sierra', 'TRI1', 'JULIO TUBON'),
(23, 'BODEGA SANGOLQUI (BSA1)', 'Sierra', 'BODEGA SANGOLQUI, Región Sierra', 'BSA1', 'VICKY MONTIEL'),
(24, 'BODEGA VALLE (BVA1)', 'Sierra', 'BODEGA VALLE, Región Sierra', 'BVA1', 'VICKY MONTIEL'),
(25, 'EXPLORER BOSQUE (EBO1)', 'Quito', 'EXPLORER BOSQUE, Región Sierra', 'EBO1', 'VICKY MONTIEL'),
(26, 'EXPLORER CONDADO (ECO1)', 'Quito', 'EXPLORER CONDADO, Región Sierra', 'ECO1', 'VICKY MONTIEL'),
(27, 'EXPLORER LATACUNGA (ELT1)', 'Latacunga', 'EXPLORER LATACUNGA, Región Sierra', 'ELT1', 'VICKY MONTIEL'),
(28, 'EXPLORER SAN LUIS (ESL1)', 'Quito', 'EXPLORER SAN LUIS, Región Sierra', 'ESL1', 'VICKY MONTIEL'),
(29, 'MARATHON BOSQUE (MBO1)', 'Quito', 'MARATHON BOSQUE, Región Sierra', 'MBO1', 'VICKY MONTIEL'),
(30, 'MARATHON CONDADO (MCO1)', 'Quito', 'MARATHON CONDADO, Región Sierra', 'MCO1', 'VICKY MONTIEL'),
(31, 'MARATHON LATACUNGA (MLT1)', 'Latacunga', 'MARATHON LATACUNGA, Región Sierra', 'MLT1', 'VICKY MONTIEL'),
(32, 'MARATHON SAN LUIS (MSL1)', 'Quito', 'MARATHON SAN LUIS, Región Sierra', 'MSL1', 'VICKY MONTIEL'),
(33, 'OUTLET DAPSILIA (ODP1)', 'Sierra', 'OUTLET DAPSILIA, Región Sierra', 'ODP1', 'VICKY MONTIEL'),
(34, 'OUTLET POMASQUI (OPO1)', 'Sierra', 'OUTLET POMASQUI, Región Sierra', 'OPO1', 'VICKY MONTIEL'),
(35, 'OUTLET VIVE PLAZA (OVP1)', 'Sierra', 'OUTLET VIVE PLAZA, Región Sierra', 'OVP1', 'VICKY MONTIEL'),
(36, 'PUMA CONDADO (PCO1)', 'Quito', 'PUMA CONDADO, Región Sierra', 'PCO1', 'VICKY MONTIEL'),
(37, 'TAF BOSQUE (FBO1)', 'Quito', 'TAF BOSQUE, Región Sierra', 'FBO1', 'VICKY MONTIEL'),
(38, 'TAF CONDADO (FCO1)', 'Quito', 'TAF CONDADO, Región Sierra', 'FCO1', 'VICKY MONTIEL'),
(39, 'TELESHOP LATACUNGA (TLT1)', 'Latacunga', 'TELESHOP LATACUNGA, Región Sierra', 'TLT1', 'VICKY MONTIEL'),
(40, 'TELESHOP SAN LUIS (TSL1)', 'Quito', 'TELESHOP SAN LUIS, Región Sierra', 'TSL1', 'VICKY MONTIEL'),
(41, 'BODEGA LOJA (BLJ1)', 'Loja', 'BODEGA LOJA, Región Sierra', 'BLJ1', 'MARFA TORRES'),
(42, 'BODEGA SAN AGUSTIN (BSG1)', 'Sierra', 'BODEGA SAN AGUSTIN, Región Sierra', 'BSG1', 'MARFA TORRES'),
(43, 'BODEGA VENTURA (BVE1)', 'Sierra', 'BODEGA VENTURA, Región Sierra', 'BVE1', 'MARFA TORRES'),
(44, 'CIKLA QUICENTRO NORTE (CQN1)', 'Quito', 'CIKLA QUICENTRO NORTE, Región Sierra', 'CQN1', 'MARFA TORRES'),
(45, 'EXPLORER LAGUNA MALL (ELG1)', 'Sierra', 'EXPLORER LAGUNA MALL, Región Sierra', 'ELG1', 'MARFA TORRES'),
(46, 'EXPLORER LOJA (ELJ1)', 'Loja', 'EXPLORER LOJA, Región Sierra', 'ELJ1', 'MARFA TORRES'),
(47, 'EXPLORER QUICENTRO NORTE (EQN1)', 'Quito', 'EXPLORER QUICENTRO NORTE, Región Sierra', 'EQN1', 'MARFA TORRES'),
(48, 'EXPLORER VENTURA (EVE1)', 'Sierra', 'EXPLORER VENTURA, Región Sierra', 'EVE1', 'MARFA TORRES'),
(49, 'MARATHON CCI (MCC1)', 'Quito', 'MARATHON CCI, Región Sierra', 'MCC1', 'MARFA TORRES'),
(50, 'MARATHON LA PLAZA (MIB1)', 'Sierra', 'MARATHON LA PLAZA, Región Sierra', 'MIB1', 'MARFA TORRES'),
(51, 'MARATHON LAGUNA (MLG1)', 'Sierra', 'MARATHON LAGUNA, Región Sierra', 'MLG1', 'MARFA TORRES'),
(52, 'MARATHON LOJA (MLJ1)', 'Loja', 'MARATHON LOJA, Región Sierra', 'MLJ1', 'MARFA TORRES'),
(53, 'MARATHON QUICENTRO NORTE (MQN1)', 'Quito', 'MARATHON QUICENTRO NORTE, Región Sierra', 'MQN1', 'MARFA TORRES'),
(54, 'OUTLET CAYAMBE (OCA1)', 'Cayambe', 'OUTLET CAYAMBE, Región Sierra', 'OCA1', 'MARFA TORRES'),
(55, 'OUTLET TULCAN (OTU1)', 'Tulcán', 'OUTLET TULCAN, Región Sierra', 'OTU1', 'MARFA TORRES'),
(56, 'PUMA QUICENTRO NORTE (PQN1)', 'Quito', 'PUMA QUICENTRO NORTE, Región Sierra', 'PQN1', 'MARFA TORRES'),
(57, 'TAF SCALA (FSC1)', 'Quito', 'TAF SCALA, Región Sierra', 'FSC1', 'MARFA TORRES'),
(58, 'UNDER ARMOUR QUICENTRO (UQN1)', 'Quito', 'UNDER ARMOUR QUICENTRO, Región Sierra', 'UQN1', 'MARFA TORRES'),
(59, 'BODEGA AMBATO (BAM1)', 'Ambato', 'BODEGA AMBATO, Región Sierra', 'BAM1', 'LUIS VALLEJOS'),
(60, 'BODEGA RECREO (BRE1)', 'Quito', 'BODEGA RECREO, Región Sierra', 'BRE1', 'LUIS VALLEJOS'),
(61, 'BODEGA SOLANDA (BSO1)', 'Quito', 'BODEGA SOLANDA, Región Sierra', 'BSO1', 'LUIS VALLEJOS'),
(62, 'CIKLA AMBATO (CAM1)', 'Ambato', 'CIKLA AMBATO, Región Sierra', 'CAM1', 'LUIS VALLEJOS'),
(63, 'CIKLA RIOCENTRO (CRC1)', 'Sierra', 'CIKLA RIOCENTRO, Región Sierra', 'CRC1', 'LUIS VALLEJOS'),
(64, 'EXPLORER AMBATO (EAM1)', 'Ambato', 'EXPLORER AMBATO, Región Sierra', 'EAM1', 'LUIS VALLEJOS'),
(65, 'EXPLORER PORTAL (ECP1)', 'Quito', 'EXPLORER PORTAL, Región Sierra', 'ECP1', 'LUIS VALLEJOS'),
(66, 'EXPLORER RECREO (ERE1)', 'Quito', 'EXPLORER RECREO, Región Sierra', 'ERE1', 'LUIS VALLEJOS'),
(67, 'EXPLORER RIOCENTRO (ERC1)', 'Sierra', 'EXPLORER RIOCENTRO, Región Sierra', 'ERC1', 'LUIS VALLEJOS'),
(68, 'MARATHON AMBATO (MAM1)', 'Ambato', 'MARATHON AMBATO, Región Sierra', 'MAM1', 'LUIS VALLEJOS'),
(69, 'MARATHON PASEO AMBATO (MAB1)', 'Ambato', 'MARATHON PASEO AMBATO, Región Sierra', 'MAB1', 'LUIS VALLEJOS'),
(70, 'MARATHON PORTAL (MCP1)', 'Quito', 'MARATHON PORTAL, Región Sierra', 'MCP1', 'LUIS VALLEJOS'),
(71, 'MARATHON RECREO (MRE1)', 'Quito', 'MARATHON RECREO, Región Sierra', 'MRE1', 'LUIS VALLEJOS'),
(72, 'MARATHON SAN FRANCISCO (MSF1)', 'Sierra', 'MARATHON SAN FRANCISCO, Región Sierra', 'MSF1', 'LUIS VALLEJOS'),
(73, 'OUTLET GASPAR (OGA1)', 'Sierra', 'OUTLET GASPAR, Región Sierra', 'OGA1', 'LUIS VALLEJOS'),
(74, 'OUTLET GRANADOS (OGR1)', 'Sierra', 'OUTLET GRANADOS, Región Sierra', 'OGR1', 'LUIS VALLEJOS'),
(75, 'PUMA PLAZA DE LAS AMERICAS (PAM1)', 'Sierra', 'PUMA PLAZA DE LAS AMERICAS, Región Sierra', 'PAM1', 'LUIS VALLEJOS'),
(76, 'TAF PORTAL (FCP1)', 'Quito', 'TAF PORTAL, Región Sierra', 'FCP1', 'LUIS VALLEJOS'),
(77, 'TAF RIOCENTRO (FRC1)', 'Sierra', 'TAF RIOCENTRO, Región Sierra', 'FRC1', 'LUIS VALLEJOS'),
(78, 'TELESHOP AMBATO (TAM1)', 'Ambato', 'TELESHOP AMBATO, Región Sierra', 'TAM1', 'LUIS VALLEJOS'),
(79, 'TELESHOP RECREO (TRE1)', 'Quito', 'TELESHOP RECREO, Región Sierra', 'TRE1', 'LUIS VALLEJOS')
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  ciudad = EXCLUDED.ciudad,
  direccion = EXCLUDED.direccion,
  unidad = EXCLUDED.unidad,
  supervisor_nombre = EXCLUDED.supervisor_nombre;

-- 2. Insertar Usuarios (Gerencia, Supervisores, Técnicos y Locales)
INSERT INTO usuarios (id, nombre, correo, usuario, contrasena, rol, tienda_id, supervisor_tiendas, estado) VALUES
(1, 'Gerencia Marathon Sports', 'gerencia@marathonsports.com', 'GEN_MS', 'GEN*MS*', 'administrador', NULL, NULL, TRUE),
(2, 'Julio Tubon (Supervisor)', 'julio.tubon@marathonsports.com', 'SUP_JT', 'SUP*JT*', 'supervisor', NULL, ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22], TRUE),
(3, 'Vicky Montiel (Supervisor)', 'vicky.montiel@marathonsports.com', 'SUP_VM', 'SUP*VM*', 'supervisor', NULL, ARRAY[23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40], TRUE),
(4, 'Marfa Torres (Supervisor)', 'marfa.torres@marathonsports.com', 'SUP_MT', 'SUP*MT*', 'supervisor', NULL, ARRAY[41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58], TRUE),
(5, 'Luis Vallejos (Supervisor)', 'luis.vallejos@marathonsports.com', 'SUP_LV', 'SUP*LV*', 'supervisor', NULL, ARRAY[59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79], TRUE),
(6, 'Efrén U (Técnico)', 'tec_eu@marathonsports.com', 'TEC_EU', 'TEC*EU*', 'tecnico', NULL, NULL, TRUE),
(7, 'Fernando S (Técnico)', 'tec_fs@marathonsports.com', 'TEC_FS', 'TEC*FS*', 'tecnico', NULL, NULL, TRUE),
(8, 'Jefe BODEGA ATAHUALPA (BAT1)', 'bat1@marathonsports.com', 'BAT1_2026', 'BAT1*2026*', 'jefe_tienda', 1, NULL, TRUE),
(9, 'Jefe BODEGA NORTE (BNO1)', 'bno1@marathonsports.com', 'BNO1_2026', 'BNO1*2026*', 'jefe_tienda', 2, NULL, TRUE),
(10, 'Jefe BODEGA RIOBAMBA (BRI1)', 'bri1@marathonsports.com', 'BRI1_2026', 'BRI1*2026*', 'jefe_tienda', 3, NULL, TRUE),
(11, 'Jefe CIKLA CUENCA (CCU1)', 'ccu1@marathonsports.com', 'CCU1_2026', 'CCU1*2026*', 'jefe_tienda', 4, NULL, TRUE),
(12, 'Jefe EXPLORER JARDIN (EJA1)', 'eja1@marathonsports.com', 'EJA1_2026', 'EJA1*2026*', 'jefe_tienda', 5, NULL, TRUE),
(13, 'Jefe EXPLORER MALL DEL RIO (ECU1)', 'ecu1@marathonsports.com', 'ECU1_2026', 'ECU1*2026*', 'jefe_tienda', 6, NULL, TRUE),
(14, 'Jefe EXPLORER RIOBAMBA (ERI1)', 'eri1@marathonsports.com', 'ERI1_2026', 'ERI1*2026*', 'jefe_tienda', 7, NULL, TRUE),
(15, 'Jefe EXPLORER SCALA (ESC1)', 'esc1@marathonsports.com', 'ESC1_2026', 'ESC1*2026*', 'jefe_tienda', 8, NULL, TRUE),
(16, 'Jefe MARATHON JARDIN (MJA1)', 'mja1@marathonsports.com', 'MJA1_2026', 'MJA1*2026*', 'jefe_tienda', 9, NULL, TRUE),
(17, 'Jefe MARATHON MALL DEL ALTO (MMA1)', 'mma1@marathonsports.com', 'MMA1_2026', 'MMA1*2026*', 'jefe_tienda', 10, NULL, TRUE),
(18, 'Jefe MARATHON MALL DEL RIO (MCU1)', 'mcu1@marathonsports.com', 'MCU1_2026', 'MCU1*2026*', 'jefe_tienda', 11, NULL, TRUE),
(19, 'Jefe MARATHON QUICENTRO SUR (MQS1)', 'mqs1@marathonsports.com', 'MQS1_2026', 'MQS1*2026*', 'jefe_tienda', 12, NULL, TRUE),
(20, 'Jefe MARATHON RIOBAMBA (MRI1)', 'mri1@marathonsports.com', 'MRI1_2026', 'MRI1*2026*', 'jefe_tienda', 13, NULL, TRUE),
(21, 'Jefe MARATHON SCALA (MSC1)', 'msc1@marathonsports.com', 'MSC1_2026', 'MSC1*2026*', 'jefe_tienda', 14, NULL, TRUE),
(22, 'Jefe OUTLET BATAN (OBT1)', 'obt1@marathonsports.com', 'OBT1_2026', 'OBT1*2026*', 'jefe_tienda', 15, NULL, TRUE),
(23, 'Jefe OUTLET GUARANDA (OGU1)', 'ogu1@marathonsports.com', 'OGU1_2026', 'OGU1*2026*', 'jefe_tienda', 16, NULL, TRUE),
(24, 'Jefe OUTLET MONAY (OMO1)', 'omo1@marathonsports.com', 'OMO1_2026', 'OMO1*2026*', 'jefe_tienda', 17, NULL, TRUE),
(25, 'Jefe TAF JARDIN (FJA1)', 'fja1@marathonsports.com', 'FJA1_2026', 'FJA1*2026*', 'jefe_tienda', 18, NULL, TRUE),
(26, 'Jefe TAF QUICENTRO SUR (FQS1)', 'fqs1@marathonsports.com', 'FQS1_2026', 'FQS1*2026*', 'jefe_tienda', 19, NULL, TRUE),
(27, 'Jefe TELESHOP JARDIN (TJA1)', 'tja1@marathonsports.com', 'TJA1_2026', 'TJA1*2026*', 'jefe_tienda', 20, NULL, TRUE),
(28, 'Jefe TELESHOP QUICENTRO SUR (TQS1)', 'tqs1@marathonsports.com', 'TQS1_2026', 'TQS1*2026*', 'jefe_tienda', 21, NULL, TRUE),
(29, 'Jefe TELESHOP RIOBAMBA (TRI1)', 'tri1@marathonsports.com', 'TRI1_2026', 'TRI1*2026*', 'jefe_tienda', 22, NULL, TRUE),
(30, 'Jefe BODEGA SANGOLQUI (BSA1)', 'bsa1@marathonsports.com', 'BSA1_2026', 'BSA1*2026*', 'jefe_tienda', 23, NULL, TRUE),
(31, 'Jefe BODEGA VALLE (BVA1)', 'bva1@marathonsports.com', 'BVA1_2026', 'BVA1*2026*', 'jefe_tienda', 24, NULL, TRUE),
(32, 'Jefe EXPLORER BOSQUE (EBO1)', 'ebo1@marathonsports.com', 'EBO1_2026', 'EBO1*2026*', 'jefe_tienda', 25, NULL, TRUE),
(33, 'Jefe EXPLORER CONDADO (ECO1)', 'eco1@marathonsports.com', 'ECO1_2026', 'ECO1*2026*', 'jefe_tienda', 26, NULL, TRUE),
(34, 'Jefe EXPLORER LATACUNGA (ELT1)', 'elt1@marathonsports.com', 'ELT1_2026', 'ELT1*2026*', 'jefe_tienda', 27, NULL, TRUE),
(35, 'Jefe EXPLORER SAN LUIS (ESL1)', 'esl1@marathonsports.com', 'ESL1_2026', 'ESL1*2026*', 'jefe_tienda', 28, NULL, TRUE),
(36, 'Jefe MARATHON BOSQUE (MBO1)', 'mbo1@marathonsports.com', 'MBO1_2026', 'MBO1*2026*', 'jefe_tienda', 29, NULL, TRUE),
(37, 'Jefe MARATHON CONDADO (MCO1)', 'mco1@marathonsports.com', 'MCO1_2026', 'MCO1*2026*', 'jefe_tienda', 30, NULL, TRUE),
(38, 'Jefe MARATHON LATACUNGA (MLT1)', 'mlt1@marathonsports.com', 'MLT1_2026', 'MLT1*2026*', 'jefe_tienda', 31, NULL, TRUE),
(39, 'Jefe MARATHON SAN LUIS (MSL1)', 'msl1@marathonsports.com', 'MSL1_2026', 'MSL1*2026*', 'jefe_tienda', 32, NULL, TRUE),
(40, 'Jefe OUTLET DAPSILIA (ODP1)', 'odp1@marathonsports.com', 'ODP1_2026', 'ODP1*2026*', 'jefe_tienda', 33, NULL, TRUE),
(41, 'Jefe OUTLET POMASQUI (OPO1)', 'opo1@marathonsports.com', 'OPO1_2026', 'OPO1*2026*', 'jefe_tienda', 34, NULL, TRUE),
(42, 'Jefe OUTLET VIVE PLAZA (OVP1)', 'ovp1@marathonsports.com', 'OVP1_2026', 'OVP1*2026*', 'jefe_tienda', 35, NULL, TRUE),
(43, 'Jefe PUMA CONDADO (PCO1)', 'pco1@marathonsports.com', 'PCO1_2026', 'PCO1*2026*', 'jefe_tienda', 36, NULL, TRUE),
(44, 'Jefe TAF BOSQUE (FBO1)', 'fbo1@marathonsports.com', 'FBO1_2026', 'FBO1*2026*', 'jefe_tienda', 37, NULL, TRUE),
(45, 'Jefe TAF CONDADO (FCO1)', 'fco1@marathonsports.com', 'FCO1_2026', 'FCO1*2026*', 'jefe_tienda', 38, NULL, TRUE),
(46, 'Jefe TELESHOP LATACUNGA (TLT1)', 'tlt1@marathonsports.com', 'TLT1_2026', 'TLT1*2026*', 'jefe_tienda', 39, NULL, TRUE),
(47, 'Jefe TELESHOP SAN LUIS (TSL1)', 'tsl1@marathonsports.com', 'TSL1_2026', 'TSL1*2026*', 'jefe_tienda', 40, NULL, TRUE),
(48, 'Jefe BODEGA LOJA (BLJ1)', 'blj1@marathonsports.com', 'BLJ1_2026', 'BLJ1*2026*', 'jefe_tienda', 41, NULL, TRUE),
(49, 'Jefe BODEGA SAN AGUSTIN (BSG1)', 'bsg1@marathonsports.com', 'BSG1_2026', 'BSG1*2026*', 'jefe_tienda', 42, NULL, TRUE),
(50, 'Jefe BODEGA VENTURA (BVE1)', 'bve1@marathonsports.com', 'BVE1_2026', 'BVE1*2026*', 'jefe_tienda', 43, NULL, TRUE),
(51, 'Jefe CIKLA QUICENTRO NORTE (CQN1)', 'cqn1@marathonsports.com', 'CQN1_2026', 'CQN1*2026*', 'jefe_tienda', 44, NULL, TRUE),
(52, 'Jefe EXPLORER LAGUNA MALL (ELG1)', 'elg1@marathonsports.com', 'ELG1_2026', 'ELG1*2026*', 'jefe_tienda', 45, NULL, TRUE),
(53, 'Jefe EXPLORER LOJA (ELJ1)', 'elj1@marathonsports.com', 'ELJ1_2026', 'ELJ1*2026*', 'jefe_tienda', 46, NULL, TRUE),
(54, 'Jefe EXPLORER QUICENTRO NORTE (EQN1)', 'eqn1@marathonsports.com', 'EQN1_2026', 'EQN1*2026*', 'jefe_tienda', 47, NULL, TRUE),
(55, 'Jefe EXPLORER VENTURA (EVE1)', 'eve1@marathonsports.com', 'EVE1_2026', 'EVE1*2026*', 'jefe_tienda', 48, NULL, TRUE),
(56, 'Jefe MARATHON CCI (MCC1)', 'mcc1@marathonsports.com', 'MCC1_2026', 'MCC1*2026*', 'jefe_tienda', 49, NULL, TRUE),
(57, 'Jefe MARATHON LA PLAZA (MIB1)', 'mib1@marathonsports.com', 'MIB1_2026', 'MIB1*2026*', 'jefe_tienda', 50, NULL, TRUE),
(58, 'Jefe MARATHON LAGUNA (MLG1)', 'mlg1@marathonsports.com', 'MLG1_2026', 'MLG1*2026*', 'jefe_tienda', 51, NULL, TRUE),
(59, 'Jefe MARATHON LOJA (MLJ1)', 'mlj1@marathonsports.com', 'MLJ1_2026', 'MLJ1*2026*', 'jefe_tienda', 52, NULL, TRUE),
(60, 'Jefe MARATHON QUICENTRO NORTE (MQN1)', 'mqn1@marathonsports.com', 'MQN1_2026', 'MQN1*2026*', 'jefe_tienda', 53, NULL, TRUE),
(61, 'Jefe OUTLET CAYAMBE (OCA1)', 'oca1@marathonsports.com', 'OCA1_2026', 'OCA1*2026*', 'jefe_tienda', 54, NULL, TRUE),
(62, 'Jefe OUTLET TULCAN (OTU1)', 'otu1@marathonsports.com', 'OTU1_2026', 'OTU1*2026*', 'jefe_tienda', 55, NULL, TRUE),
(63, 'Jefe PUMA QUICENTRO NORTE (PQN1)', 'pqn1@marathonsports.com', 'PQN1_2026', 'PQN1*2026*', 'jefe_tienda', 56, NULL, TRUE),
(64, 'Jefe TAF SCALA (FSC1)', 'fsc1@marathonsports.com', 'FSC1_2026', 'FSC1*2026*', 'jefe_tienda', 57, NULL, TRUE),
(65, 'Jefe UNDER ARMOUR QUICENTRO (UQN1)', 'uqn1@marathonsports.com', 'UQN1_2026', 'UQN1*2026*', 'jefe_tienda', 58, NULL, TRUE),
(66, 'Jefe BODEGA AMBATO (BAM1)', 'bam1@marathonsports.com', 'BAM1_2026', 'BAM1*2026*', 'jefe_tienda', 59, NULL, TRUE),
(67, 'Jefe BODEGA RECREO (BRE1)', 'bre1@marathonsports.com', 'BRE1_2026', 'BRE1*2026*', 'jefe_tienda', 60, NULL, TRUE),
(68, 'Jefe BODEGA SOLANDA (BSO1)', 'bso1@marathonsports.com', 'BSO1_2026', 'BSO1*2026*', 'jefe_tienda', 61, NULL, TRUE),
(69, 'Jefe CIKLA AMBATO (CAM1)', 'cam1@marathonsports.com', 'CAM1_2026', 'CAM1*2026*', 'jefe_tienda', 62, NULL, TRUE),
(70, 'Jefe CIKLA RIOCENTRO (CRC1)', 'crc1@marathonsports.com', 'CRC1_2026', 'CRC1*2026*', 'jefe_tienda', 63, NULL, TRUE),
(71, 'Jefe EXPLORER AMBATO (EAM1)', 'eam1@marathonsports.com', 'EAM1_2026', 'EAM1*2026*', 'jefe_tienda', 64, NULL, TRUE),
(72, 'Jefe EXPLORER PORTAL (ECP1)', 'ecp1@marathonsports.com', 'ECP1_2026', 'ECP1*2026*', 'jefe_tienda', 65, NULL, TRUE),
(73, 'Jefe EXPLORER RECREO (ERE1)', 'ere1@marathonsports.com', 'ERE1_2026', 'ERE1*2026*', 'jefe_tienda', 66, NULL, TRUE),
(74, 'Jefe EXPLORER RIOCENTRO (ERC1)', 'erc1@marathonsports.com', 'ERC1_2026', 'ERC1*2026*', 'jefe_tienda', 67, NULL, TRUE),
(75, 'Jefe MARATHON AMBATO (MAM1)', 'mam1@marathonsports.com', 'MAM1_2026', 'MAM1*2026*', 'jefe_tienda', 68, NULL, TRUE),
(76, 'Jefe MARATHON PASEO AMBATO (MAB1)', 'mab1@marathonsports.com', 'MAB1_2026', 'MAB1*2026*', 'jefe_tienda', 69, NULL, TRUE),
(77, 'Jefe MARATHON PORTAL (MCP1)', 'mcp1@marathonsports.com', 'MCP1_2026', 'MCP1*2026*', 'jefe_tienda', 70, NULL, TRUE),
(78, 'Jefe MARATHON RECREO (MRE1)', 'mre1@marathonsports.com', 'MRE1_2026', 'MRE1*2026*', 'jefe_tienda', 71, NULL, TRUE),
(79, 'Jefe MARATHON SAN FRANCISCO (MSF1)', 'msf1@marathonsports.com', 'MSF1_2026', 'MSF1*2026*', 'jefe_tienda', 72, NULL, TRUE),
(80, 'Jefe OUTLET GASPAR (OGA1)', 'oga1@marathonsports.com', 'OGA1_2026', 'OGA1*2026*', 'jefe_tienda', 73, NULL, TRUE),
(81, 'Jefe OUTLET GRANADOS (OGR1)', 'ogr1@marathonsports.com', 'OGR1_2026', 'OGR1*2026*', 'jefe_tienda', 74, NULL, TRUE),
(82, 'Jefe PUMA PLAZA DE LAS AMERICAS (PAM1)', 'pam1@marathonsports.com', 'PAM1_2026', 'PAM1*2026*', 'jefe_tienda', 75, NULL, TRUE),
(83, 'Jefe TAF PORTAL (FCP1)', 'fcp1@marathonsports.com', 'FCP1_2026', 'FCP1*2026*', 'jefe_tienda', 76, NULL, TRUE),
(84, 'Jefe TAF RIOCENTRO (FRC1)', 'frc1@marathonsports.com', 'FRC1_2026', 'FRC1*2026*', 'jefe_tienda', 77, NULL, TRUE),
(85, 'Jefe TELESHOP AMBATO (TAM1)', 'tam1@marathonsports.com', 'TAM1_2026', 'TAM1*2026*', 'jefe_tienda', 78, NULL, TRUE),
(86, 'Jefe TELESHOP RECREO (TRE1)', 'tre1@marathonsports.com', 'TRE1_2026', 'TRE1*2026*', 'jefe_tienda', 79, NULL, TRUE)
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  correo = EXCLUDED.correo,
  usuario = EXCLUDED.usuario,
  contrasena = EXCLUDED.contrasena,
  rol = EXCLUDED.rol,
  tienda_id = EXCLUDED.tienda_id,
  supervisor_tiendas = EXCLUDED.supervisor_tiendas,
  estado = EXCLUDED.estado;

-- 3. Insertar Casos Iniciales de Demostración
INSERT INTO casos (id, tienda_id, creado_por, categoria, descripcion, prioridad_nivel, estado, tecnico_asignado_id, fecha_creacion, fecha_limite_sla, fecha_cierre) VALUES
(1001, 70, 77, 'Fallo Eléctrico Total', 'Cortocircuito en el breaker principal del tablero de calzado en Marathon Portal (MCP1).', 1, 'concluido', 6, NOW() - INTERVAL '36 hours', NOW() - INTERVAL '32 hours', NOW() - INTERVAL '30 hours'),
(1002, 49, 56, 'Falla de Climatización / Aire Acondicionado', 'El condensador central gotea directamente sobre la mercadería de exhibición en Marathon CCI (MCC1).', 2, 'en_proceso', 7, NOW() - INTERVAL '5 hours', NOW() + INTERVAL '19 hours', NULL),
(1003, 9, 15, 'Daño en Mobiliario / Exhibidores', 'Trizadura en el acrílico del exhibidor central de balones en Marathon Jardín (MJA1).', 4, 'pendiente', NULL, NOW() - INTERVAL '2 hours', NOW() + INTERVAL '166 hours', NULL),
(1004, 30, 36, 'Fuga de Agua / Inundación', 'Fuga en tubería de bodega en Marathon Condado (MCO1). Riesgo de daño a mercadería.', 1, 'pendiente', NULL, NOW() - INTERVAL '1 hour', NOW() + INTERVAL '3 hours', NULL)
ON CONFLICT (id) DO UPDATE SET
  tienda_id = EXCLUDED.tienda_id,
  creado_por = EXCLUDED.creado_por,
  categoria = EXCLUDED.categoria,
  descripcion = EXCLUDED.descripcion,
  prioridad_nivel = EXCLUDED.prioridad_nivel,
  estado = EXCLUDED.estado,
  tecnico_asignado_id = EXCLUDED.tecnico_asignado_id;
