import type { User } from './types';

export const DEFAULT_USERS: User[] = [
  {
    "id": 1,
    "nombre": "Gerencia Marathon Sports",
    "correo": "gerencia@marathonsports.com",
    "usuario": "GEN_MS",
    "contrasena": "GEN*MS*",
    "rol": "administrador",
    "estado": true
  },
  {
    "id": 2,
    "nombre": "Julio Tubon (Supervisor)",
    "correo": "julio.tubon@marathonsports.com",
    "usuario": "SUP_JT",
    "contrasena": "SUP*JT*",
    "rol": "supervisor",
    "passwordCambiado": false,
    "supervisorTiendas": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22
    ],
    "estado": true
  },
  {
    "id": 3,
    "nombre": "Vicky Montiel (Supervisor)",
    "correo": "vicky.montiel@marathonsports.com",
    "usuario": "SUP_VM",
    "contrasena": "SUP*VM*",
    "rol": "supervisor",
    "passwordCambiado": false,
    "supervisorTiendas": [
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40
    ],
    "estado": true
  },
  {
    "id": 4,
    "nombre": "Marfa Torres (Supervisor)",
    "correo": "marfa.torres@marathonsports.com",
    "usuario": "SUP_MT",
    "contrasena": "SUP*MT*",
    "rol": "supervisor",
    "passwordCambiado": false,
    "supervisorTiendas": [
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      58
    ],
    "estado": true
  },
  {
    "id": 5,
    "nombre": "Luis Vallejos (Supervisor)",
    "correo": "luis.vallejos@marathonsports.com",
    "usuario": "SUP_LV",
    "contrasena": "SUP*LV*",
    "rol": "supervisor",
    "supervisorTiendas": [
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66,
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76,
      77,
      78,
      79
    ],
    "estado": true
  },
  {
    "id": 6,
    "nombre": "Efrén U (Técnico)",
    "correo": "tec_eu@marathonsports.com",
    "usuario": "TEC_EU",
    "contrasena": "TEC*EU*",
    "rol": "tecnico",
    "estado": true
  },
  {
    "id": 7,
    "nombre": "Fernando S (Técnico)",
    "correo": "tec_fs@marathonsports.com",
    "usuario": "TEC_FS",
    "contrasena": "TEC*FS*",
    "rol": "tecnico",
    "estado": true
  },
  {
    "id": 8,
    "nombre": "Local BODEGA ATAHUALPA (BAT1)",
    "correo": "bat1@marathonsports.com",
    "usuario": "BAT1_2026",
    "contrasena": "BAT1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 1,
    "estado": true
  },
  {
    "id": 9,
    "nombre": "Local BODEGA NORTE (BNO1)",
    "correo": "bno1@marathonsports.com",
    "usuario": "BNO1_2026",
    "contrasena": "BNO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 2,
    "estado": true
  },
  {
    "id": 10,
    "nombre": "Local BODEGA RIOBAMBA (BRI1)",
    "correo": "bri1@marathonsports.com",
    "usuario": "BRI1_2026",
    "contrasena": "BRI1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 3,
    "estado": true
  },
  {
    "id": 11,
    "nombre": "Local CIKLA CUENCA (CCU1)",
    "correo": "ccu1@marathonsports.com",
    "usuario": "CCU1_2026",
    "contrasena": "CCU1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 4,
    "estado": true
  },
  {
    "id": 12,
    "nombre": "Local EXPLORER JARDIN (EJA1)",
    "correo": "eja1@marathonsports.com",
    "usuario": "EJA1_2026",
    "contrasena": "EJA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 5,
    "estado": true
  },
  {
    "id": 13,
    "nombre": "Local EXPLORER MALL DEL RIO (ECU1)",
    "correo": "ecu1@marathonsports.com",
    "usuario": "ECU1_2026",
    "contrasena": "ECU1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 6,
    "estado": true
  },
  {
    "id": 14,
    "nombre": "Local EXPLORER RIOBAMBA (ERI1)",
    "correo": "eri1@marathonsports.com",
    "usuario": "ERI1_2026",
    "contrasena": "ERI1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 7,
    "estado": true
  },
  {
    "id": 15,
    "nombre": "Local EXPLORER SCALA (ESC1)",
    "correo": "esc1@marathonsports.com",
    "usuario": "ESC1_2026",
    "contrasena": "ESC1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 8,
    "estado": true
  },
  {
    "id": 16,
    "nombre": "Local MARATHON JARDIN (MJA1)",
    "correo": "mja1@marathonsports.com",
    "usuario": "MJA1_2026",
    "contrasena": "MJA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 9,
    "estado": true
  },
  {
    "id": 17,
    "nombre": "Local MARATHON MALL DEL ALTO (MMA1)",
    "correo": "mma1@marathonsports.com",
    "usuario": "MMA1_2026",
    "contrasena": "MMA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 10,
    "estado": true
  },
  {
    "id": 18,
    "nombre": "Local MARATHON MALL DEL RIO (MCU1)",
    "correo": "mcu1@marathonsports.com",
    "usuario": "MCU1_2026",
    "contrasena": "MCU1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 11,
    "estado": true
  },
  {
    "id": 19,
    "nombre": "Local MARATHON QUICENTRO SUR (MQS1)",
    "correo": "mqs1@marathonsports.com",
    "usuario": "MQS1_2026",
    "contrasena": "MQS1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 12,
    "estado": true
  },
  {
    "id": 20,
    "nombre": "Local MARATHON RIOBAMBA (MRI1)",
    "correo": "mri1@marathonsports.com",
    "usuario": "MRI1_2026",
    "contrasena": "MRI1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 13,
    "estado": true
  },
  {
    "id": 21,
    "nombre": "Local MARATHON SCALA (MSC1)",
    "correo": "msc1@marathonsports.com",
    "usuario": "MSC1_2026",
    "contrasena": "MSC1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 14,
    "estado": true
  },
  {
    "id": 22,
    "nombre": "Local OUTLET BATAN (OBT1)",
    "correo": "obt1@marathonsports.com",
    "usuario": "OBT1_2026",
    "contrasena": "OBT1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 15,
    "estado": true
  },
  {
    "id": 23,
    "nombre": "Local OUTLET GUARANDA (OGU1)",
    "correo": "ogu1@marathonsports.com",
    "usuario": "OGU1_2026",
    "contrasena": "OGU1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 16,
    "estado": true
  },
  {
    "id": 24,
    "nombre": "Local OUTLET MONAY (OMO1)",
    "correo": "omo1@marathonsports.com",
    "usuario": "OMO1_2026",
    "contrasena": "OMO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 17,
    "estado": true
  },
  {
    "id": 25,
    "nombre": "Local TAF JARDIN (FJA1)",
    "correo": "fja1@marathonsports.com",
    "usuario": "FJA1_2026",
    "contrasena": "FJA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 18,
    "estado": true
  },
  {
    "id": 26,
    "nombre": "Local TAF QUICENTRO SUR (FQS1)",
    "correo": "fqs1@marathonsports.com",
    "usuario": "FQS1_2026",
    "contrasena": "FQS1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 19,
    "estado": true
  },
  {
    "id": 27,
    "nombre": "Local TELESHOP JARDIN (TJA1)",
    "correo": "tja1@marathonsports.com",
    "usuario": "TJA1_2026",
    "contrasena": "TJA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 20,
    "estado": true
  },
  {
    "id": 28,
    "nombre": "Local TELESHOP QUICENTRO SUR (TQS1)",
    "correo": "tqs1@marathonsports.com",
    "usuario": "TQS1_2026",
    "contrasena": "TQS1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 21,
    "estado": true
  },
  {
    "id": 29,
    "nombre": "Local TELESHOP RIOBAMBA (TRI1)",
    "correo": "tri1@marathonsports.com",
    "usuario": "TRI1_2026",
    "contrasena": "TRI1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 22,
    "estado": true
  },
  {
    "id": 30,
    "nombre": "Local BODEGA SANGOLQUI (BSA1)",
    "correo": "bsa1@marathonsports.com",
    "usuario": "BSA1_2026",
    "contrasena": "BSA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 23,
    "estado": true
  },
  {
    "id": 31,
    "nombre": "Local BODEGA VALLE (BVA1)",
    "correo": "bva1@marathonsports.com",
    "usuario": "BVA1_2026",
    "contrasena": "BVA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 24,
    "estado": true
  },
  {
    "id": 32,
    "nombre": "Local EXPLORER BOSQUE (EBO1)",
    "correo": "ebo1@marathonsports.com",
    "usuario": "EBO1_2026",
    "contrasena": "EBO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 25,
    "estado": true
  },
  {
    "id": 33,
    "nombre": "Local EXPLORER CONDADO (ECO1)",
    "correo": "eco1@marathonsports.com",
    "usuario": "ECO1_2026",
    "contrasena": "ECO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 26,
    "estado": true
  },
  {
    "id": 34,
    "nombre": "Local EXPLORER LATACUNGA (ELT1)",
    "correo": "elt1@marathonsports.com",
    "usuario": "ELT1_2026",
    "contrasena": "ELT1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 27,
    "estado": true
  },
  {
    "id": 35,
    "nombre": "Local EXPLORER SAN LUIS (ESL1)",
    "correo": "esl1@marathonsports.com",
    "usuario": "ESL1_2026",
    "contrasena": "ESL1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 28,
    "estado": true
  },
  {
    "id": 36,
    "nombre": "Local MARATHON BOSQUE (MBO1)",
    "correo": "mbo1@marathonsports.com",
    "usuario": "MBO1_2026",
    "contrasena": "MBO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 29,
    "estado": true
  },
  {
    "id": 37,
    "nombre": "Local MARATHON CONDADO (MCO1)",
    "correo": "mco1@marathonsports.com",
    "usuario": "MCO1_2026",
    "contrasena": "MCO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 30,
    "estado": true
  },
  {
    "id": 38,
    "nombre": "Local MARATHON LATACUNGA (MLT1)",
    "correo": "mlt1@marathonsports.com",
    "usuario": "MLT1_2026",
    "contrasena": "MLT1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 31,
    "estado": true
  },
  {
    "id": 39,
    "nombre": "Local MARATHON SAN LUIS (MSL1)",
    "correo": "msl1@marathonsports.com",
    "usuario": "MSL1_2026",
    "contrasena": "MSL1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 32,
    "estado": true
  },
  {
    "id": 40,
    "nombre": "Local OUTLET DAPSILIA (ODP1)",
    "correo": "odp1@marathonsports.com",
    "usuario": "ODP1_2026",
    "contrasena": "ODP1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 33,
    "estado": true
  },
  {
    "id": 41,
    "nombre": "Local OUTLET POMASQUI (OPO1)",
    "correo": "opo1@marathonsports.com",
    "usuario": "OPO1_2026",
    "contrasena": "OPO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 34,
    "estado": true
  },
  {
    "id": 42,
    "nombre": "Local OUTLET VIVE PLAZA (OVP1)",
    "correo": "ovp1@marathonsports.com",
    "usuario": "OVP1_2026",
    "contrasena": "OVP1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 35,
    "estado": true
  },
  {
    "id": 43,
    "nombre": "Local PUMA CONDADO (PCO1)",
    "correo": "pco1@marathonsports.com",
    "usuario": "PCO1_2026",
    "contrasena": "PCO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 36,
    "estado": true
  },
  {
    "id": 44,
    "nombre": "Local TAF BOSQUE (FBO1)",
    "correo": "fbo1@marathonsports.com",
    "usuario": "FBO1_2026",
    "contrasena": "FBO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 37,
    "estado": true
  },
  {
    "id": 45,
    "nombre": "Local TAF CONDADO (FCO1)",
    "correo": "刺激FCO1_2026".replace('刺激', ''),
    "contrasena": "FCO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 38,
    "estado": true
  },
  {
    "id": 46,
    "nombre": "Local TELESHOP LATACUNGA (TLT1)",
    "correo": "tlt1@marathonsports.com",
    "usuario": "TLT1_2026",
    "contrasena": "TLT1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 39,
    "estado": true
  },
  {
    "id": 47,
    "nombre": "Local TELESHOP SAN LUIS (TSL1)",
    "correo": "tsl1@marathonsports.com",
    "usuario": "TSL1_2026",
    "contrasena": "TSL1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 40,
    "estado": true
  },
  {
    "id": 48,
    "nombre": "Local BODEGA LOJA (BLJ1)",
    "correo": "blj1@marathonsports.com",
    "usuario": "BLJ1_2026",
    "contrasena": "BLJ1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 41,
    "estado": true
  },
  {
    "id": 49,
    "nombre": "Local BODEGA SAN AGUSTIN (BSG1)",
    "correo": "bsg1@marathonsports.com",
    "usuario": "BSG1_2026",
    "contrasena": "BSG1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 42,
    "estado": true
  },
  {
    "id": 50,
    "nombre": "Local BODEGA VENTURA (BVE1)",
    "correo": "bve1@marathonsports.com",
    "usuario": "BVE1_2026",
    "contrasena": "BVE1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 43,
    "estado": true
  },
  {
    "id": 51,
    "nombre": "Local CIKLA QUICENTRO NORTE (CQN1)",
    "correo": "cqn1@marathonsports.com",
    "usuario": "CQN1_2026",
    "contrasena": "CQN1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 44,
    "estado": true
  },
  {
    "id": 52,
    "nombre": "Local EXPLORER LAGUNA MALL (ELG1)",
    "correo": "elg1@marathonsports.com",
    "usuario": "ELG1_2026",
    "contrasena": "ELG1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 45,
    "estado": true
  },
  {
    "id": 53,
    "nombre": "Local EXPLORER LOJA (ELJ1)",
    "correo": "elj1@marathonsports.com",
    "usuario": "ELJ1_2026",
    "contrasena": "ELJ1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 46,
    "estado": true
  },
  {
    "id": 54,
    "nombre": "Local EXPLORER QUICENTRO NORTE (EQN1)",
    "correo": "eqn1@marathonsports.com",
    "usuario": "EQN1_2026",
    "contrasena": "EQN1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 47,
    "estado": true
  },
  {
    "id": 55,
    "nombre": "Local EXPLORER VENTURA (EVE1)",
    "correo": "eve1@marathonsports.com",
    "usuario": "EVE1_2026",
    "contrasena": "EVE1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 48,
    "estado": true
  },
  {
    "id": 56,
    "nombre": "Local MARATHON CCI (MCC1)",
    "correo": "mcc1@marathonsports.com",
    "usuario": "MCC1_2026",
    "contrasena": "MCC1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 49,
    "estado": true
  },
  {
    "id": 57,
    "nombre": "Local MARATHON LA PLAZA (MIB1)",
    "correo": "mib1@marathonsports.com",
    "usuario": "MIB1_2026",
    "contrasena": "MIB1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 50,
    "estado": true
  },
  {
    "id": 58,
    "nombre": "Local MARATHON LAGUNA (MLG1)",
    "correo": "mlg1@marathonsports.com",
    "usuario": "MLG1_2026",
    "contrasena": "MLG1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 51,
    "estado": true
  },
  {
    "id": 59,
    "nombre": "Local MARATHON LOJA (MLJ1)",
    "correo": "mlj1@marathonsports.com",
    "usuario": "MLJ1_2026",
    "contrasena": "MLJ1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 52,
    "estado": true
  },
  {
    "id": 60,
    "nombre": "Local MARATHON QUICENTRO NORTE (MQN1)",
    "correo": "mqn1@marathonsports.com",
    "usuario": "MQN1_2026",
    "contrasena": "MQN1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 53,
    "estado": true
  },
  {
    "id": 61,
    "nombre": "Local OUTLET CAYAMBE (OCA1)",
    "correo": "oca1@marathonsports.com",
    "usuario": "OCA1_2026",
    "contrasena": "OCA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 54,
    "estado": true
  },
  {
    "id": 62,
    "nombre": "Local OUTLET TULCAN (OTU1)",
    "correo": "otu1@marathonsports.com",
    "usuario": "OTU1_2026",
    "contrasena": "OTU1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 55,
    "estado": true
  },
  {
    "id": 63,
    "nombre": "Local PUMA QUICENTRO NORTE (PQN1)",
    "correo": "pqn1@marathonsports.com",
    "usuario": "PQN1_2026",
    "contrasena": "PQN1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 56,
    "estado": true
  },
  {
    "id": 64,
    "nombre": "Local TAF SCALA (FSC1)",
    "correo": "fsc1@marathonsports.com",
    "usuario": "FSC1_2026",
    "contrasena": "FSC1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 57,
    "estado": true
  },
  {
    "id": 65,
    "nombre": "Local UNDER ARMOUR QUICENTRO (UQN1)",
    "correo": "uqn1@marathonsports.com",
    "usuario": "UQN1_2026",
    "contrasena": "UQN1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 58,
    "estado": true
  },
  {
    "id": 66,
    "nombre": "Local BODEGA AMBATO (BAM1)",
    "correo": "bam1@marathonsports.com",
    "usuario": "BAM1_2026",
    "contrasena": "BAM1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 59,
    "estado": true
  },
  {
    "id": 67,
    "nombre": "Local BODEGA RECREO (BRE1)",
    "correo": "bre1@marathonsports.com",
    "usuario": "BRE1_2026",
    "contrasena": "BRE1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 60,
    "estado": true
  },
  {
    "id": 68,
    "nombre": "Local BODEGA SOLANDA (BSO1)",
    "correo": "bso1@marathonsports.com",
    "usuario": "BSO1_2026",
    "contrasena": "BSO1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 61,
    "estado": true
  },
  {
    "id": 69,
    "nombre": "Local CIKLA AMBATO (CAM1)",
    "correo": "cam1@marathonsports.com",
    "usuario": "CAM1_2026",
    "contrasena": "CAM1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 62,
    "estado": true
  },
  {
    "id": 70,
    "nombre": "Local CIKLA RIOCENTRO (CRC1)",
    "correo": "crc1@marathonsports.com",
    "usuario": "CRC1_2026",
    "contrasena": "CRC1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 63,
    "estado": true
  },
  {
    "id": 71,
    "nombre": "Local EXPLORER AMBATO (EAM1)",
    "correo": "eam1@marathonsports.com",
    "usuario": "EAM1_2026",
    "contrasena": "EAM1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 64,
    "estado": true
  },
  {
    "id": 72,
    "nombre": "Local EXPLORER PORTAL (ECP1)",
    "correo": "ecp1@marathonsports.com",
    "usuario": "ECP1_2026",
    "contrasena": "ECP1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 65,
    "estado": true
  },
  {
    "id": 73,
    "nombre": "Local EXPLORER RECREO (ERE1)",
    "correo": "ere1@marathonsports.com",
    "usuario": "ERE1_2026",
    "contrasena": "ERE1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 66,
    "estado": true
  },
  {
    "id": 74,
    "nombre": "Local EXPLORER RIOCENTRO (ERC1)",
    "correo": "erc1@marathonsports.com",
    "usuario": "ERC1_2026",
    "contrasena": "ERC1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 67,
    "estado": true
  },
  {
    "id": 75,
    "nombre": "Local MARATHON AMBATO (MAM1)",
    "correo": "mam1@marathonsports.com",
    "usuario": "MAM1_2026",
    "contrasena": "MAM1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 68,
    "estado": true
  },
  {
    "id": 76,
    "nombre": "Local MARATHON PASEO AMBATO (MAB1)",
    "correo": "mab1@marathonsports.com",
    "usuario": "MAB1_2026",
    "contrasena": "MAB1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 69,
    "estado": true
  },
  {
    "id": 77,
    "nombre": "Local MARATHON PORTAL (MCP1)",
    "correo": "mcp1@marathonsports.com",
    "usuario": "MCP1_2026",
    "contrasena": "MCP1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 70,
    "estado": true
  },
  {
    "id": 78,
    "nombre": "Local MARATHON RECREO (MRE1)",
    "correo": "mre1@marathonsports.com",
    "usuario": "MRE1_2026",
    "contrasena": "MRE1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 71,
    "estado": true
  },
  {
    "id": 79,
    "nombre": "Local MARATHON SAN FRANCISCO (MSF1)",
    "correo": "msf1@marathonsports.com",
    "usuario": "MSF1_2026",
    "contrasena": "MSF1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 72,
    "estado": true
  },
  {
    "id": 80,
    "nombre": "Local OUTLET GASPAR (OGA1)",
    "correo": "oga1@marathonsports.com",
    "usuario": "OGA1_2026",
    "contrasena": "OGA1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 73,
    "estado": true
  },
  {
    "id": 81,
    "nombre": "Local OUTLET GRANADOS (OGR1)",
    "correo": "ogr1@marathonsports.com",
    "usuario": "OGR1_2026",
    "contrasena": "OGR1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 74,
    "estado": true
  },
  {
    "id": 82,
    "nombre": "Local PUMA PLAZA DE LAS AMERICAS (PAM1)",
    "correo": "pam1@marathonsports.com",
    "usuario": "PAM1_2026",
    "contrasena": "PAM1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 75,
    "estado": true
  },
  {
    "id": 83,
    "nombre": "Local TAF PORTAL (FCP1)",
    "correo": "fcp1@marathonsports.com",
    "usuario": "FCP1_2026",
    "contrasena": "FCP1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 76,
    "estado": true
  },
  {
    "id": 84,
    "nombre": "Local TAF RIOCENTRO (FRC1)",
    "correo": "frc1@marathonsports.com",
    "usuario": "FRC1_2026",
    "contrasena": "FRC1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 77,
    "estado": true
  },
  {
    "id": 85,
    "nombre": "Local TELESHOP AMBATO (TAM1)",
    "correo": "tam1@marathonsports.com",
    "usuario": "TAM1_2026",
    "contrasena": "TAM1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 78,
    "estado": true
  },
  {
    "id": 86,
    "nombre": "Local TELESHOP RECREO (TRE1)",
    "correo": "tre1@marathonsports.com",
    "usuario": "TRE1_2026",
    "contrasena": "TRE1*2026*",
    "rol": "jefe_tienda",
    "tiendaId": 79,
    "estado": true
  }
];
